name: "Publish"

on: 
  push:
    branches: ["main"]


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hashnode publish
        id: publish_hashnode              
        uses: raunakgurud09/hashnode-publish@v1
        with:
          host: "levelupdevs.hashnode.dev"
          file: "post/blog/dynamic-routing-static-regeneration.md"
          hashnode_key: ${{secrets.HASHNODE_KEY}}
      - name: Get get output
        run: echo "me- ${{steps.publish_hashnode.outputs.result_json}} length ${{steps.publish_hashnode.outputs.result_summary}}"
